// Programmes officiels par classe.
// La structure est identique côté client (client/src/programmes.js).
export const PROGRAMMES = {
    '6e': [
      {
        trimestre: 'Premier trimestre : L\'ordinateur et son environnement',
        chapitres: [
          "Qu'est-ce qu'un ordinateur ?",
          'Allumer et éteindre l\'ordinateur',
          'Le bureau de l\'ordinateur',
          'La souris : cliquer et double-cliquer',
          'La souris : clic droit et glisser-déposer',
          'Le clavier : les zones principales',
          'Les fichiers et les dossiers',
          'Créer et organiser des dossiers',
          'Enregistrer un fichier',
          'Projet du trimestre',
        ],
      },
      {
        trimestre: 'Deuxième trimestre : Le traitement de texte (Word)',
        chapitres: [
          'Découvrir le logiciel Word',
          'Saisir du texte',
          'Les accents et caractères spéciaux',
          'Corriger ses erreurs',
          'La sélection de texte',
          'La mise en forme : Gras, Italique, Souligné',
          'La police et la taille du texte',
          'La couleur du texte',
          "L'alignement du texte",
          'Enregistrer et ouvrir un document',
          'Projet du trimestre',
        ],
      },
      {
        trimestre: 'Troisième trimestre : Dactylographie et dessin',
        chapitres: [
          'La position des mains sur le clavier',
          'La rangée de repos',
          'Les voyelles',
          'La touche Entrée et la barre d\'espace',
          'Entraînement général de dactylographie',
          'Découvrir le logiciel Paint',
          'Les formes géométriques dans Paint',
          'Les couleurs et le remplissage',
          'Enregistrer un dessin',
          'Intégrer une image dans Word',
          "Projet final de l'année",
        ],
      },
    ],
  
    '5e': [
      {
        trimestre: 'Premier trimestre : Rappel des bases + Word perfectionnement (partie 1)',
        chapitres: [
          "(Rappel) L'ordinateur et ses composants",
          '(Rappel) La souris, le clavier et les fichiers',
          '(Rappel) Découvrir Word et saisir du texte',
          '(Rappel) Mise en forme de base dans Word',
          '(Rappel) Enregistrer et ouvrir un document',
          'Les retraits de paragraphe',
          "L'interligne et l'espacement",
          'Les listes à puces',
          'Les listes numérotées',
          'Insérer des images depuis un fichier',
          "L'habillage du texte autour des images",
          'Positionner les images librement',
          'Les bordures et trames de fond',
          'Projet du premier trimestre',
        ],
      },
      {
        trimestre: 'Deuxième trimestre : Word perfectionnement (partie 2) + Dactylographie',
        chapitres: [
          'Créer un tableau simple',
          'Saisir et se déplacer dans un tableau',
          'Mettre en forme un tableau',
          'Insérer et supprimer des lignes et colonnes',
          'Fusionner des cellules',
          'Les tabulations : principe',
          'Les tabulations : types et utilisation',
          'Le correcteur orthographique',
          'Le correcteur grammatical',
          'La position des mains sur le clavier',
          'La rangée de repos et les voyelles',
          'Entraînement de dactylographie',
          'Projet du deuxième trimestre',
        ],
      },
      {
        trimestre: 'Troisième trimestre : Initiation à PowerPoint + Projet final',
        chapitres: [
          'Découvrir PowerPoint',
          'Créer une présentation',
          'Saisir du texte dans les diapositives',
          'Ajouter des images',
          "Les modes d'affichage",
          'Lancer le diaporama',
          'Mise en forme du texte dans PowerPoint',
          'Les listes à puces dans PowerPoint',
          "Projet final de l'année",
        ],
      },
    ],
  
    '4e': [
      {
        trimestre: 'Premier trimestre : Rappel des bases + PowerPoint perfectionnement (partie 1)',
        chapitres: [
          "(Rappel) L'ordinateur, la souris et le clavier",
          '(Rappel) Les fichiers et dossiers',
          '(Rappel) Word — Saisie et mise en forme',
          '(Rappel) Word — Listes, images et tableaux',
          '(Rappel) Word — Enregistrer et ouvrir',
          'Révision de PowerPoint',
          "La structure d'un exposé",
          'Les arrière-plans et thèmes personnalisés',
          'Les formes et dessins',
          'Les SmartArt (diagrammes)',
          'Les tableaux dans PowerPoint',
          'La mise en forme professionnelle',
          'Les transitions entre diapositives',
          "Les animations d'objets",
          'Projet du premier trimestre',
        ],
      },
      {
        trimestre: 'Deuxième trimestre : PowerPoint perfectionnement (partie 2) + Présentation orale',
        chapitres: [
          'Les notes de présentation',
          'Le mode présentateur',
          'Les liens hypertextes',
          'Insérer des vidéos',
          'Insérer des sons',
          'La communication orale',
          'Bien utiliser ses diapositives',
          'Préparer son exposé',
          'Projet du deuxième trimestre',
        ],
      },
      {
        trimestre: 'Troisième trimestre : Initiation à Excel + Projet final',
        chapitres: [
          'Découvrir Excel',
          'Les cellules',
          'Saisir des données',
          'Modifier le contenu des cellules',
          'Largeur des colonnes et hauteur des lignes',
          'Mise en forme des cellules',
          'Les bordures',
          'Fusionner des cellules',
          'Les premières formules',
          'La fonction SOMME',
          "Projet final de l'année",
        ],
      },
    ],
  
    '3e': [
      {
        trimestre: 'Premier trimestre : Rappel des bases + Excel perfectionnement (partie 1)',
        chapitres: [
          "(Rappel) L'ordinateur, la souris et le clavier",
          '(Rappel) Les fichiers et dossiers',
          '(Rappel) Word — Saisie et mise en forme',
          '(Rappel) Word — Listes, images et tableaux',
          '(Rappel) PowerPoint — Créer une présentation',
          '(Rappel) Excel — Découvrir et saisir des données',
          'La fonction MOYENNE',
          'Les fonctions MAX et MIN',
          'La fonction NB',
          'Les séries automatiques',
          'Les références relatives',
          'Les références absolues',
          'Les formats de nombres',
          "Mise en page pour l'impression",
          'Projet du premier trimestre',
        ],
      },
      {
        trimestre: 'Deuxième trimestre : Excel perfectionnement (partie 2) + Graphiques',
        chapitres: [
          'Introduction aux graphiques',
          'Créer un graphique en histogramme',
          'Personnaliser un histogramme',
          'Créer un graphique en secteurs',
          'Créer un graphique en courbes',
          'Changer de type de graphique',
          'Préparer une enquête',
          "Saisir les données de l'enquête",
          'Analyser les résultats',
          "Créer les graphiques de l'enquête",
          'Projet du deuxième trimestre',
        ],
      },
      {
        trimestre: 'Troisième trimestre : Word documents longs + Projet final',
        chapitres: [
          'Les styles : introduction',
          'Utiliser les styles de titre',
          'Modifier un style',
          'Le mode plan',
          'Insérer une table des matières',
          'Les en-têtes et pieds de page',
          'Les numéros de page',
          'Les sauts de page',
          'Les notes de bas de page',
          "Projet final de l'année",
        ],
      },
    ],
  
    '2nd': [
      {
        trimestre: 'Premier trimestre : Rappel des bases + Word avancé + Publipostage',
        chapitres: [
          "(Rappel) L'ordinateur et les raccourcis clavier",
          '(Rappel) Les fichiers et dossiers',
          '(Rappel) Word — Saisie et mise en forme',
          '(Rappel) Word — Listes, images et tableaux',
          '(Rappel) Excel — Découvrir et saisir des données',
          '(Rappel) Excel — Formules simples et SOMME',
          '(Rappel) PowerPoint — Créer une présentation',
          'Les raccourcis clavier essentiels',
          'Navigation rapide dans un document',
          'Le publipostage : introduction',
          'Créer la lettre type',
          'Créer la base de données',
          'Fusionner les documents',
          'Les étiquettes et enveloppes',
          'Les formulaires dans Word',
          'Protéger un formulaire',
          'Projet du premier trimestre',
        ],
      },
      {
        trimestre: 'Deuxième trimestre : Excel avancé + Formules de facture + Analyse',
        chapitres: [
          'La fonction SI',
          'Les fonctions ET et OU',
          'Fonctions SI imbriquées',
          'La mise en forme conditionnelle',
          'Mise en forme conditionnelle avancée',
          'Trier les données',
          'Filtrer les données',
          'Filtres personnalisés',
          'La validation des données',
          'Formules de facture — Calcul MONTANT',
          'Formules de facture — Calcul PHTVA',
          'Formules de facture — Calcul REMISE',
          'Formules de facture — Calcul NET COMMERCIAL',
          'Formules de facture — Calcul TVA 20%',
          'Formules de facture — Net à payer et style monétaire',
          'Travaux pratiques — Établir une facture complète',
          'Projet du deuxième trimestre',
        ],
      },
      {
        trimestre: 'Troisième trimestre : PowerPoint avancé + Projet intégrateur',
        chapitres: [
          'Les présentations non linéaires',
          'Créer un sommaire interactif',
          'Insérer des vidéos',
          'Insérer des sons',
          'Les masques de diapositives',
          'Utiliser un masque personnalisé',
          'Projet intégrateur : préparation',
          'Projet intégrateur : réalisation',
          'Projet intégrateur : présentation',
        ],
      },
    ],
  
    'Terminale': [
      {
        trimestre: 'Premier trimestre : Rappel des bases + Word académique + CV et lettre',
        chapitres: [
          "(Rappel) L'ordinateur et les raccourcis clavier",
          '(Rappel) Les fichiers et dossiers',
          '(Rappel) Word — Saisie et mise en forme',
          '(Rappel) Word — Listes, images et tableaux',
          '(Rappel) Excel — Découvrir et saisir des données',
          '(Rappel) Excel — Formules simples et SOMME',
          '(Rappel) PowerPoint — Créer une présentation',
          'Le travail collaboratif',
          'Partager un document',
          'La co-édition en temps réel',
          'Les commentaires',
          'Le suivi des modifications',
          'Créer un modèle de document',
          'Les sections dans Word',
          'Les citations et la bibliographie',
          'Le CV : les principes',
          'Créer son CV avec Word',
          'La lettre de motivation',
          'Projet du premier trimestre',
        ],
      },
      {
        trimestre: 'Deuxième trimestre : Excel avancé + Formules de facture + Simulations',
        chapitres: [
          'La fonction RECHERCHEV',
          'Les tableaux croisés dynamiques : introduction',
          'Créer un tableau croisé dynamique',
          'Personnaliser un tableau croisé dynamique',
          'Les graphiques croisés dynamiques',
          'Formules de facture — Calcul MONTANT',
          'Formules de facture — Calcul PHTVA',
          'Formules de facture — Calcul REMISE',
          'Formules de facture — Calcul NET COMMERCIAL',
          'Formules de facture — Calcul TVA 20%',
          'Formules de facture — Net à payer et style monétaire',
          'Travaux pratiques — Établir une facture complète',
          'La valeur cible',
          'Les scénarios',
          'Créer un tableau de bord',
          'Projet du deuxième trimestre',
        ],
      },
      {
        trimestre: 'Troisième trimestre : PowerPoint pour le Grand Oral + Projet final',
        chapitres: [
          'Le Grand Oral : les attentes',
          'Structurer sa présentation',
          'Créer un support visuel efficace',
          'Les graphiques pour convaincre',
          'Les images et métaphores visuelles',
          'La répétition générale',
          'Amélioration après feedback',
          'Projet final : dossier de candidature complet',
        ],
      },
    ],
  };